# Use a Linux distribution (Ubuntu in this case) as the base image
FROM ubuntu:20.04

# Set the working directory inside the container
WORKDIR /app

# Update the package index and install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Add your all other dependencies here
